services:
  evently.api:
    image: evently.api
    container_name: Evently.Api
    build:
      context: .
      dockerfile: src/Evently.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DOTNET_ENVIRONMENT=Production
      
  evently.postgres:
    image: postgres:latest
    container_name: Evently.Db
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  evently.mailpit:
    image: axllent/mailpit
    container_name: Evently.Smtp
    volumes:
      - ./.containers/smpt:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
